# Generated by Django 5.2.7 on 2025-10-19 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=120)),
                ('nombre', models.CharField(max_length=200)),
                ('fuente', models.CharField(blank=True, max_length=120, null=True)),
                ('linkapowerbi', models.URLField()),
                ('esprivado', models.BooleanField(default=False)),
                ('notebook_path', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'ordering': ['area', 'nombre'],
            },
        ),
    ]
